services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo_data:/data/db

  frontend:
    image: bloglist-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    depends_on:
      - mongo

  backend:
    image: bloglist-backend
    container_name: bloglist-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules # https://stackoverflow.com/a/60194067
    depends_on:
      - frontend
      - mongo

volumes:
  mongo_data:
  node_modules:
